FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY *.sln .
COPY PraticeV1.API/PraticeV1.API.csproj ./PraticeV1.API/
COPY PracticeV1.Application/PracticeV1.Application.csproj ./PracticeV1.Application/
COPY PracticeV1.Domain/PracticeV1.Domain.csproj ./PracticeV1.Domain/
COPY PracticeV1.Infrastructure/PracticeV1.Infrastructure.csproj ./PracticeV1.Infrastructure/ 

run dotnet restore "PraticeV1.API/PraticeV1.API.csproj"

# Copy everything else and build
copy . .


# Build the project
workdir /src/PraticeV1.API
run dotnet build "PraticeV1.API.csproj" -c Release -o /app/build --no-restore



FROM build AS publish
RUN dotnet publish "PraticeV1.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app



COPY --from=publish /app/publish .

RUN add-user  --disabled-password --gecos "" appuser && chown -R appuser /app

EXPOSE 8080

ENV ASPNETCORE_URLS=http://+:8080
ENV ASPNETCORE_ENVIRONMENT=Production

# Run the application
ENTRYPOINT ["dotnet", "PraticeV1.API.dll"]